version: "3"

volumes:
    postgres_data:
        driver: local

services:
    products_database:
        image: "postgres:10.5"
        container_name: "products_database"
        ports:
            - 5431:5432
        volumes:
            - ./db-init/init-product-database.sql:/docker-entrypoint-initdb.d/init.sql

    customers_database:
        image: "postgres:10.5"
        container_name: "customers_database"
        ports:
            - 5432:5432
        volumes:
            - ./db-init/init-customer-database.sql:/docker-entrypoint-initdb.d/init.sql

    orders_database:
        image: "postgres:10.5"
        container_name: "orders_database"
        ports:
            - 5439:5432
        volumes:
            - ./db-init/init-order-database.sql:/docker-entrypoint-initdb.d/init.sql

    carts_database:
        image: "postgres:10.5"
        container_name: "carts_database"
        ports:
            - 5434:5432
        volumes:
            - ./db-init/init-cart-database.sql:/docker-entrypoint-initdb.d/init.sql

    monitoring:
        image: "prom/prometheus"
        container_name: "super-visor"
        ports:
          - 9090:9090
        volumes:
          - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    keycloak_db:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: password
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: Pa55w0rd
            # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
            #JDBC_PARAMS: "ssl=true"
        ports:
            - 5555:5555
        depends_on:
            - keycloak_db
