global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

# tag::adocPrometheus[]
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'Customer API'
    static_configs:
      - targets: ['host.docker.internal:8082']
  - job_name: 'Product API'
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'Order API'
    static_configs:
      - targets: ['host.docker.internal:8083']
  - job_name: 'Cart API'
    static_configs:
      - targets: ['host.docker.internal:8084']
  - job_name: 'Stock API'
    static_configs:
      - targets: ['host.docker.internal:8085']
# end::adocPrometheus[]
