CREATE ROLE admin WITH LOGIN PASSWORD 'admin';

CREATE ROLE orderadmin WITH LOGIN PASSWORD 'orderadmin' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE orders_database;
GRANT ALL PRIVILEGES ON DATABASE orders_database TO orderadmin;
GRANT ALL PRIVILEGES ON DATABASE orders_database TO admin;