CREATE ROLE admin WITH LOGIN PASSWORD 'admin';

CREATE ROLE cartadmin WITH LOGIN PASSWORD 'cartadmin' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE carts_database;
GRANT ALL PRIVILEGES ON DATABASE carts_database TO cartadmin;
GRANT ALL PRIVILEGES ON DATABASE carts_database TO admin;


