CREATE ROLE admin WITH LOGIN PASSWORD 'admin';

CREATE ROLE customeradmin WITH LOGIN PASSWORD 'customeradmin' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE customers_database;
GRANT ALL PRIVILEGES ON DATABASE customers_database TO customeradmin;
GRANT ALL PRIVILEGES ON DATABASE customers_database TO admin;


